# Generated by Django 4.1.5 on 2023-01-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action_adventure_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('released_date', models.CharField(max_length=10, unique=True)),
                ('overview', models.CharField(max_length=200, unique=True)),
                ('poster_path', models.CharField(max_length=50, unique=True)),
                ('genres', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
