# Generated by Django 4.1.5 on 2023-01-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crolling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_adventure_model',
            name='movie_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
