# Generated by Django 4.1.5 on 2023-01-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crolling', '0002_action_adventure_model_movie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('released_date', models.CharField(max_length=10, unique=True)),
                ('overview', models.CharField(max_length=200, unique=True)),
                ('poster_path', models.CharField(max_length=50, unique=True)),
                ('genres', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drama_Famile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('released_date', models.CharField(max_length=10, unique=True)),
                ('overview', models.CharField(max_length=200, unique=True)),
                ('poster_path', models.CharField(max_length=50, unique=True)),
                ('genres', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fantasy_SF_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('released_date', models.CharField(max_length=10, unique=True)),
                ('overview', models.CharField(max_length=200, unique=True)),
                ('poster_path', models.CharField(max_length=50, unique=True)),
                ('genres', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Romance_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('released_date', models.CharField(max_length=10, unique=True)),
                ('overview', models.CharField(max_length=200, unique=True)),
                ('poster_path', models.CharField(max_length=50, unique=True)),
                ('genres', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thriller_Fear_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('released_date', models.CharField(max_length=10, unique=True)),
                ('overview', models.CharField(max_length=200, unique=True)),
                ('poster_path', models.CharField(max_length=50, unique=True)),
                ('genres', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVmovie_Animation_Music_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('released_date', models.CharField(max_length=10, unique=True)),
                ('overview', models.CharField(max_length=200, unique=True)),
                ('poster_path', models.CharField(max_length=50, unique=True)),
                ('genres', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
