# Generated by Django 4.1.5 on 2023-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crolling', '0003_comedy_model_drama_famile_model_fantasy_sf_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action_adventure_model',
            name='genres',
            field=models.CharField(max_length=10),
        ),
    ]
