# Generated by Django 4.1.5 on 2023-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crolling', '0004_alter_action_adventure_model_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedy_model',
            name='genres',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drama_famile_model',
            name='genres',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fantasy_sf_model',
            name='genres',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='romance_model',
            name='genres',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thriller_fear_model',
            name='genres',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tvmovie_animation_music_model',
            name='genres',
            field=models.CharField(max_length=10),
        ),
    ]
